### ISSUE TITLE
Professor Page

### ISSUE THREAD

**Issue by gursheyss** [SCE-Development/spartan-compass#11]
Prereq: #14 

When searching for classes, we'll also want to be able to click on a professors name and view a "profile" of them, showing what classes they teach.

- [x] Create a [dynamic route](https://kit.svelte.dev/docs/routing#page-page-server-js) called `/professor/[name]`
- [x] In the `+page.server.ts`, we want to fetch the professor's information along with what classes they teach
- [x] Using that returned data, put it into components on the `+page.svelte` (put components under `$lib/components/Professor Profile` 

It also has to be responsive, use chrome's devtools to check how it looks on mobile

**Comment by jonathanguven** [comment]
anyone good at frontend and ui stuff wanna help with this last task 💀. I already finished the information fetching so only the frontend is left.
