### ISSUE TITLE
Add Ratings to database

### ISSUE THREAD

**Issue by gursheyss** [SCE-Development/spartan-compass#14]
Since we now have authentication, we're going to need to add the ratings system to our database.
- [ ] Create reviewsTable: It should have an id, a userid that references a user, a professorid that references a professor, and a rating thats >= 1 and <= 5, a comment, and a created at timestamp

Add this to our `schema.ts`

**Comment by jonathanguven** [comment]
column for course? bc they might suck at one course but be good at another

**Comment by gursheyss** [comment]
Yea
