### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by gursheyss** [SCE-Development/spartan-compass#7]
For our navigation, we'll create a header similar to the one on [clark](https://sce.sjsu.edu/), with DaisyUI.

It also has to be responsive, use chrome's devtools to check how it looks on mobile

This header should have hrefs to: Home, About, Login, Signup

You'll need to
- [x] Create the buttons
- [x] Move our login component to the header
- [x] Create routes

Utilize Sveltekit's layout files for this so we can have it persist across routes

**Comment by jonathanguven** [comment]
<img width="1782" alt="image" src="https://github.com/SCE-Development/sjsu-rmp/assets/128879714/2de066c9-63c4-492d-89c3-51a77614f3a0">
this header from bruinwalk looks p good dont rip it off 100% tho

**Comment by jonathanguven** [comment]
https://daisyui.com/components/navbar/
